version: '3.9'
services:
  redis:
    image: "redis:alpine"
    volumes:
      - ./tmp/redis:/var/lib/redis/data
  web:
    build:
      context: ./
      target: production
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - '8080:8080'
    depends_on:
      - redis
